// <auto-generated />
namespace Collaboration.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_specifications_register : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_specifications_register));
        
        string IMigrationMetadata.Id
        {
            get { return "202012201527277_added_specifications_register"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
